kind: Pod
apiVersion: v1
metadata:
  name: fare-service-pod
  labels:
    app: fare-service
spec:
  containers:
   - name: fare-service-container
     image: navkkrnair/10-2019-fare-service:2.0
     imagePullPolicy: Always
     env:
      - name: CONFIG-SERVICE
        value: config-service
     livenessProbe:
       httpGet:
         path: /actuator/health
         port: 8080
       initialDelaySeconds: 100  
     ports:
      - name: container-port
        containerPort: 8080
        protocol: TCP
        
---

apiVersion: v1
kind: Service
metadata:
  name: fare-service
  labels:
    app: fare-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: container-port
    protocol: TCP
  selector:
    app: fare-service